### ISSUE TITLE
lightsensors not working on ROS Kinetic

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/raspimouse_sim#5]
lightsensors are not working on ROS Kinetic.

```
$ rostopic echo /raspimouse_gazebo/lf_scan                                                                                                                                        
header:                                                                                                                                                                           
  seq: 0                                                                                                                                                                          
  stamp:                                                                                                                                                                          
    secs: 3                                                                                                                                                                       
    nsecs:  51000000                                                                                                                                                              
  frame_id: lf                                                                                                                                                                    
angle_min: -0.15000000596                                                                                                                                                         
angle_max: 0.15000000596                                                                                                                                                          
angle_increment: -0.300000011921                                                                                                                                                  
time_increment: 0.0                                                                                                                                                               
scan_time: 0.0                                                                                                                                                                    
range_min: 0.00999999977648                                                                                                                                                       
range_max: 0.600000023842                                                                                                                                                         
ranges: []                                                                                                                                                                        
intensities: []                                                                                                                                                                   
---                                                                                                                                                                               
header:                                                                                                                                                                           
  seq: 1                                                                                                                                                                          
  stamp:                                                                                                                                                                          
    secs: 3                                                                                                                                                                       
    nsecs: 101000000                                                                                                                                                              
  frame_id: lf                                                                                                                                                                    
angle_min: -0.15000000596                                                                                                                                                         
angle_max: 0.15000000596                                                                                                                                                          
angle_increment: -0.300000011921            
time_increment: 0.0                         
scan_time: 0.0                              
range_min: 0.00999999977648                 
range_max: 0.600000023842                   
ranges: []
intensities: []
```

It should be like this.
```
ubuntu@ubuntu:~$ rostopic echo /raw_raspimouse/lf/scan 
header: 
  seq: 43
  stamp: 
    secs: 2
    nsecs: 202000000
  frame_id: lf
angle_min: -0.15000000596
angle_max: 0.15000000596
angle_increment: -0.300000011921
time_increment: 0.0
scan_time: 0.0
range_min: 0.00999999977648
range_max: 0.600000023842
ranges: [0.5359607934951782]
intensities: [0.0]
---
header: 
  seq: 44
  stamp: 
    secs: 2
    nsecs: 252000000
  frame_id: lf
angle_min: -0.15000000596
angle_max: 0.15000000596
angle_increment: -0.300000011921
time_increment: 0.0
scan_time: 0.0
range_min: 0.00999999977648
range_max: 0.600000023842
ranges: [0.6000000238418579]
intensities: [0.0]
---
header: 
  seq: 45
  stamp: 
    secs: 2
    nsecs: 302000000
  frame_id: lf
angle_min: -0.15000000596
angle_max: 0.15000000596
angle_increment: -0.300000011921
time_increment: 0.0
scan_time: 0.0
range_min: 0.00999999977648
range_max: 0.600000023842
ranges: [0.6000000238418579]
intensities: [0.0]
```
